### ISSUE TITLE
Suggestion: Split out Javascript CI

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#2141]
## Proposal

Currently one of the Linux platform tests also includes the Javascript build. 

As it is not necessary to run the C++ build before the Javascript build, the suggestion is to split out the latter
so hopefully both can run in parallel to reduce overall time but also be able to just run either build independently of the other.

The workflow could look something like this:
```yaml
        - name: Linux_GCC_13_Python311
          os: ubuntu-24.04
          compiler: gcc
          compiler_version: "13"
          python: 3.11

        - name: Linux_ems_2_0_20_Javascript
          os: ubuntu-24.04
          compiler_version: "None"
          python: None
          build_javascript: ON
```
With the `emscripten` version as part of the build label. If different variants are required in the future it is easier to control as well (e.g. handling different rendering backends such as adding a path tracer variant).
